# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

## This was modified from a standard GitHub Actions template (original template is MIT license)

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        # cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv pytest
        uv venv
        .venv/Scripts/activate
        uv pip install .      
    #    uv pip install tensorflow==2.8.* tensorflow-addons>=0.16.1 keras<3.0.0
    #   uv is not compatible with the current setup of pyproject.toml (particularly for the [tensorflow] tag). For some reason the command above also creates an error
    - name: Lint with ruff
      run: |
        uvx ruff check isosegdenoise/
    - name: Test with pytest
      run: |
        pytest
    #   python /tests/test_seg.py
